fail_fast: true

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo nightly fmt
        entry: cargo +nightly fmt --
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster

      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check --all
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster

      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo clippy --all-targets --all-features --tests --benches -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false # This makes it a lot faster
